# Generated by Django 3.0.8 on 2021-10-12 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='text',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 19, 15, 23, 689557, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 19, 15, 23, 688597, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 19, 15, 23, 687764, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_path',
            field=models.CharField(default='images/anonymous.jpg', max_length=64),
        ),
    ]
